apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      name: train-schedule
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: train-schedule
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - port: 8080
    nodePort: 8080
    protocol: TCP
